### ISSUE TITLE
Failing to mirror public repo

### ISSUE THREAD

**Issue by muse-sisay** [MephistoXoL/Docker-Gitea#2]
Before updating to the latest images, I could point to a remote repo and have gitea mirror it. After upgrading to `V1.14.1`, I am getting this message `Migrating from https://github.com/MephistoXoL/Docker-Gitea/ failed.` When I check logs, I see this :

```bash
app_1  | 2021/05/05 11:15:33 Completed GET /user/task/16?_csrf=UPQJUlFGObkAOjRrGiixZau5SEA6MTYyMDIxMjI5MDM3MTQ5MzM2MA 500 Internal Server Error in 118.546375ms
```
What am I doing wrong ? 

My docker-compose 
```yml
version: '3.2'

services:
  app:
    container_name: gitea_app
    image: mephistoxol/gitea
    restart: unless-stopped
    # Traefik v1.7 optional
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
```

Thank you in advance
